### ISSUE TITLE
Links from Pro Drivers to Database Pages

### ISSUE THREAD

**Issue by akgold** [rstudio/db.rstudio.com#101]
It'd be awesome if the bullets on this page for each driver type linked to the relevant database page.

https://db.rstudio.com/rstudio/pro-drivers/

@blairj09 - happy to just do this unless you have any reason to hold off?

**Comment by blairj09** [comment]
@akgold I like the idea and #103 adds the missing links. However, certain DB specific pages do not include references to the pro drivers, which I think should be updated before we link to them from the Pro Drivers page.

For example, see:
https://db.rstudio.com/databases/big-query/
https://db.rstudio.com/databases/my-sql/
