### ISSUE TITLE
Disclaimer for pro driver licensing

### ISSUE THREAD

**Issue by nwstephens** [rstudio/db.rstudio.com#105]
## Is your request to add new, update existing, or removing content?

Add new content.

### Reason for requesting changes

Adding information about the licensing of Pro Drivers.

## Pro Product

Pro Drivers

## Does this need to go out with a specific release?

Not tied to a specific Pro Drivers release.

## Priority
Select the appropriate Priority label:

- Medium Severity - The issue reports incorrect documentation or documentation creating a confusing user experience.

## Link to the documentation

Add the following information to https://docs.rstudio.com/pro-drivers/:

> RStudio has licensed high-quality, commercial ODBC drivers for many common data sources from Simba Technologies, a subsidiary of Magnitude Software. We absorb the cost of this license and provide them at no additional charge to current paying customers to be used exclusively with RStudio professional products, including the RStudio Team bundle, RStudio Server Pro, RStudio Connect, and Shiny Server Pro. We do not sell or offer RStudio Professional Drivers for use with our free and open-source server or desktop software, and our license does not permit the drivers to be used with these products.

### Does this documentation live in this repo?

Yes, lives in this repo.

**Comment by akgold** [comment]
This looks like it's been resolved. Reopen if not.
