### ISSUE TITLE
Avoid .connection_string

### ISSUE THREAD

**Issue by hadley** [rstudio/db.rstudio.com#3]
And instead use named parameters to `dbConnect()`

**Comment by jimhester** [comment]
Agreed! `.connection_string` is really only exists for the case where someone has an existing connection string they are copy pasting.

Anytime you are writing a new connection string it is more readable to use the named parameters.

**Comment by edgararuiz** [comment]
Right there with you guys.  Currently, `.connection_string` is in the samples because it's what the Connections pane snippet uses to build the connection code.   I'll make sure to remove them as part of my IDE v1.1 reference clean-up.

**Comment by hadley** [comment]
We should also make sure that the IDE doesn't generate it either.

**Comment by jimhester** [comment]
I opened an issue to that effect (https://github.com/rstudio/odbc-install/issues/18)

**Comment by nwstephens** [comment]
This enhancement has been completed. See [rstudio/odbc-install#18](https://github.com/rstudio/odbc-install/issues/18)
