### ISSUE TITLE
Managing credentials section

### ISSUE THREAD

**Issue by hadley** [rstudio/db.rstudio.com#4]
I think you need a short section on managing credentials in between "run queries safely" and "deploying content". This would basically say that you should never store a password in your R script and never type it into the console.  

For now, this section would discuss three options to avoid this:

* Use `rstudioapi::askForPassword()`
* Use keyring
* Use an environment variable

**Comment by bborgesr** [comment]
A while back, [I created a repo](https://github.com/bborgesr/yaml-db-security) to demo one option for database credentials:

> An example of how to have a minimal level of security when using database credentials in deployed Shiny apps

It recommends literally the minimum (a .gitignored yml file that is stored safely in your server). Just in case this is useful for whomever is writing the article.

**Comment by edgararuiz** [comment]
Thanks @bborgesr !

**Comment by edgararuiz** [comment]
@hadley - Yes, I believe that's the intent of a new page listed in the Database Project document.  Here's the item copied from the list:

Securing Credentials - New  article - It discusses the config and keyring packages.  It will also recommend `prompt password` as a first option.  This is ‘you should never have your credentials in your code’ article.

Does this look right to you?

**Comment by hadley** [comment]
Sounds good.
