### ISSUE TITLE
Add MonetDB database

### ISSUE THREAD

**Issue by edgararuiz** [rstudio/db.rstudio.com#57]
@hannesmuehleisen - I think that we should include MonetDB and MonetDBLite-R to the Databases section.  Any suggestions or objections to that?  If none, would you have any recommendations for connecting that are different from what in the README in the repo (https://github.com/hannesmuehleisen/MonetDBLite-R)?

**Comment by hannesmuehleisen** [comment]
No objections, and you may use the text and examples.

**Comment by hannesmuehleisen** [comment]
thanks!
